### PR TITLE
Fix & uniformize the deploy command

### PR DESCRIPTION
**Pull request by MarioUhrik**
I fixed and uniformized the commands among `README.md` and `deploy.sh`.
Both of them were broken in separate ways.

I removed the `TODO`, since I didn't understand why it's there.

### CODE REVIEW

**Comment by bernardhalas** [comment]
Thank you for the fix Mario.
For the `TODO` part, I was wondering whether there could be a way to make this git-repo a remote base for the `ytt`. Unfortunately I haven't found such a way. Would you have an idea?

**Review by bernardhalas — APPROVED** [review]
Thank you for the PR.

**Comment by MarioUhrik** [comment]
@bernardhalas  You're welcome!

> For the TODO part, I was wondering whether there could be a way to make this git-repo a remote base for the ytt. Unfortunately I haven't found such a way. Would you have an idea?

You considered the "remote base" feature the main advantage of YTT, I thought you had already found a way :smile: 
I am not the YTT expert here, but it seems it could be doable via:
```
$ ytt --help
...
  -f, --file stringArray                            File (ie local path, HTTP URL, -) (can be specified multiple times)
```
E.g. it's probably something like this:
```
$ ytt -f https://github.com/kubernetes-sigs/kustomize/tree/master/examples/helloWorld
```

In Kustomize, it would look something like this:

```
$ cat kustomization.yaml
resources:
- https://github.com/kubernetes-sigs/kustomize/tree/master/examples/helloWorld
```

**Comment by bernardhalas** [comment]
It would be great if there was a built-in native git repo support. Which is the case neither for kustomize nor for ytt. Remote base is obviously supported by both, e.g.:

```shell
ytt -f data.yaml -f https://raw.githubusercontent.com/Berops/claudie-k8s-monitoring/main/deploy/1-libs/labels.lib.yaml -f https://raw.githubusercontent.com/Berops/claudie-k8s-monitoring/main/deploy/1-libs/metadata.lib.yaml -f https://raw.githubusercontent.com/Berops/claudie-k8s-monitoring/main/deploy/2-alertmanager/deploy.yaml
```
But this way it's a bit ugly and needs some wrapper. Not a problem though, we can provide one later. For the moment we can live with `git clone && ytt -f data.yaml -f deploy`.

**Comment by MarioUhrik** [comment]
I believe that kustomize offers native git support, according to this:
```
The URL format is an HTTPS or SSH git clone URL with an optional directory and some query string parameters.
```
(source: https://github.com/kubernetes-sigs/kustomize/blob/master/examples/remoteBuild.md)

I totally agree with you that otherwise it would be nearly useless as a feature.

---

Now, whether YTT has a native git support or not, I don't know, but I'm inclined to believe you're right that it doesn't.

> Either we provide a wrapper or we will live with  `git clone && ytt -f data.yaml -f claudie-k8s-monitoring/deploy`

I agree this seems to be the only theoretical way forward for a "remote base" via YTT at the moment.
For the purposes of this (or any other) project's README, I think the `git clone` is presumed and implied.
I think we can leave it out, in which case the README is fine.
Shall we merge this?

**Comment by bernardhalas** [comment]
Good to know that kustomize can work directly against git repos.

Yes, let's merge this.

**Pull request merged**
